name: Unit test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache build
      uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-build
    - name: Test
      run: swift test --enable-code-coverage -v 2>&1 | xcpretty
    - name: Export code coverage
      run: xcrun llvm-cov export -format="lcov" .build/x86_64-apple-macosx/debug/UsbtKitPackageTests.xctest/Contents/MacOS/UsbtKitPackageTests -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata > .build/usbtkit-coverage.lcov
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: .build/usbtkit-coverage.lcov
        fail_ci_if_error: true
        verbose: true
