name: Unit test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  macOS-5_3:
    name: Unit test macOS Swift (5.3)
    runs-on: macos-11.0
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache build
      uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-unit-test-xcode-12
    - name: Test
      run: swift test --enable-code-coverage -v 2>&1 | xcpretty
    - name: Export code coverage
      if: github.ref == 'refs/heads/develop'
      run: xcrun llvm-cov export -format="lcov" .build/x86_64-apple-macosx/debug/UsbtKitPackageTests.xctest/Contents/MacOS/UsbtKitPackageTests -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata > .build/usbtkit-coverage.lcov
    - name: Upload code coverage
      if: github.ref == 'refs/heads/develop'
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: .build/usbtkit-coverage.lcov
        fail_ci_if_error: true
        verbose: true
  macOS-5_2:
      name: Unit test macOS Swift (5.2)
      runs-on: macos-11.0
      env: 
        DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-unit-test-xcode-12
      - name: Test
        run: swift test --enable-code-coverage -v 2>&1 | xcpretty
      - name: Export code coverage
        if: github.ref == 'refs/heads/develop'
        run: xcrun llvm-cov export -format="lcov" .build/x86_64-apple-macosx/debug/UsbtKitPackageTests.xctest/Contents/MacOS/UsbtKitPackageTests -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata > .build/usbtkit-coverage.lcov
      - name: Upload code coverage
        if: github.ref == 'refs/heads/develop'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: .build/usbtkit-coverage.lcov
          fail_ci_if_error: true
          verbose: true